### ISSUE TITLE
Missing multilingual support

### ISSUE THREAD

**Issue by xmeadow** [EchoInMirror/EchoInMirror#29]
I tested EIM and noticed that it does not support multiple languages, which makes it difficult for users who don't speak chinese to test features and functions. You would just need to setup the prequesition in thesoftware and setup the pipeline in code. Translating Software is something the community can do!

I can imagine that you plan to have multilingual support, so that more people can use it and appreciate it but I also wanted to be the first who give you an issue in github 😁. 

Thank you for your hard work and dedication.

**Comment by ShirasawaSama** [comment]
Thank you for your support. First of all, multilingual support is indeed in our plan, but this requirement may be realized in a very late stage.

Projects/内测目标:

![IMG_20231230_050138](https://github.com/EchoInMirror/EchoInMirror/assets/17093811/64855dc6-f535-4160-a6d1-15b84b4ce36e)

The reason is that there are still many functions to be improved. Many texts may change at any time. At present, many texts are only used for placeholders.

At the same time, we are also looking for a localization solution that can cross platforms and have a better experience.

**Comment by ShirasawaSama** [comment]
https://github.com/EchoInMirror/EchoInMirror/blob/master/langs/src/commonMain/kotlin/com/eimsound/daw/language/langs/En.kt
